columns:
  id: int
  NumDots: int
  SubdomainLevel: int
  PathLevel: int
  UrlLength: int
  NumDash: int
  NumDashInHostname: int
  AtSymbol: int
  TildeSymbol: int
  NumUnderscore: int
  NumPercent: int
  NumQueryComponents: int
  NumAmpersand: int
  NumHash: int
  NumNumericChars: int
  NoHttps: int
  RandomString: int
  IpAddress: int
  DomainInSubdomains: int
  DomainInPaths: int
  HttpsInHostname: int
  HostnameLength: int
  PathLength: int
  QueryLength: int
  DoubleSlashInPath: int
  NumSensitiveWords: int
  EmbeddedBrandName: int
  PctExtHyperlinks: float
  PctExtResourceUrls: float
  ExtFavicon: int
  InsecureForms: int
  RelativeFormAction: int
  ExtFormAction: int
  AbnormalFormAction: int
  PctNullSelfRedirectHyperlinks: float
  FrequentDomainNameMismatch: int
  FakeLinkInStatusBar: int
  RightClickDisabled: int
  PopUpWindow: int
  SubmitInfoToEmail: int
  IframeOrFrame: int
  MissingTitle: int
  ImagesOnlyInForm: int
  SubdomainLevelRT: float
  UrlLengthRT: float
  PctExtResourceUrlsRT: float
  AbnormalExtFormActionR: int
  ExtMetaScriptLinkRT: float
  PctExtNullSelfRedirectHyperlinksRT: float
  CLASS_LABEL: int   # target column (0 = legitimate, 1 = phishing)

numerical_columns:
  - NumDots
  - SubdomainLevel
  - PathLevel
  - UrlLength
  - NumDash
  - NumDashInHostname
  - AtSymbol
  - TildeSymbol
  - NumUnderscore
  - NumPercent
  - NumQueryComponents
  - NumAmpersand
  - NumHash
  - NumNumericChars
  - NoHttps
  - RandomString
  - IpAddress
  - DomainInSubdomains
  - DomainInPaths
  - HttpsInHostname
  - HostnameLength
  - PathLength
  - QueryLength
  - DoubleSlashInPath
  - NumSensitiveWords
  - EmbeddedBrandName
  - PctExtHyperlinks
  - PctExtResourceUrls
  - ExtFavicon
  - InsecureForms
  - RelativeFormAction
  - ExtFormAction
  - AbnormalFormAction
  - PctNullSelfRedirectHyperlinks
  - FrequentDomainNameMismatch
  - FakeLinkInStatusBar
  - RightClickDisabled
  - PopUpWindow
  - SubmitInfoToEmail
  - IframeOrFrame
  - MissingTitle
  - ImagesOnlyInForm
  - SubdomainLevelRT
  - UrlLengthRT
  - PctExtResourceUrlsRT
  - AbnormalExtFormActionR
  - ExtMetaScriptLinkRT
  - PctExtNullSelfRedirectHyperlinksRT
